<a href="https://colab.research.google.com/github/vishrutxraj/JIOIN-Python-pre-term-course/blob/main/JIOIn_py_class_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY


In [5]:
import numpy as np
a = np.array([3,430,69,82])
b = np.array([34,56,78,90])


add = np.add(a,b)
sub = np.subtract(a,b)
multiply = np.multiply(a,b)
divide = np.divide(a,b)

print(add)
print(sub)
print(multiply)
print(divide)

[ 37 486 147 172]
[-31 374  -9  -8]
[  102 24080  5382  7380]
[0.08823529 7.67857143 0.88461538 0.91111111]
